name: Deploy to Maspoli Clean
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: Web
jobs:
  deploy:
    name: Deploy
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 📂 Sync files in server Maspoli Clean
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.maspoliclean.com.br
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /public_html/
          dry-run: false #COLOCAR TRUE SÓ IRA SIMULAR
          exclude: |
            .git/